name: Update Scholar Publications

on:
  schedule:
    - cron: '0 0 * * SUN'  # Updates every Sunday at midnight
  workflow_dispatch:

jobs:
  update-publications:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install scholarly package and compatible httpx
        run: |
          pip install scholarly httpx==0.26.0

      - name: Fetch and Update Publications
        run: |
          python fetch_scholar.py

      - name: Commit and Push Changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add list-of-publications.md
          git diff --quiet && git diff --staged --quiet || git commit -m "Automated update: publications from Google Scholar"
          git push
